using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DataAccess
{
    /// <summary>
    /// Controller class for discounts
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DiscountController
    {
        // Preload our schema..
        Discount thisSchemaLoad = new Discount();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DiscountCollection FetchAll()
        {
            DiscountCollection coll = new DiscountCollection();
            Query qry = new Query(Discount.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DiscountCollection FetchByID(object Id)
        {
            DiscountCollection coll = new DiscountCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DiscountCollection FetchByQuery(Query qry)
        {
            DiscountCollection coll = new DiscountCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Discount.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Discount.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Name,string Description,int ValueX,DateTime? FromDate,DateTime? ToDate)
	    {
		    Discount item = new Discount();
		    
            item.Name = Name;
            
            item.Description = Description;
            
            item.ValueX = ValueX;
            
            item.FromDate = FromDate;
            
            item.ToDate = ToDate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Name,string Description,int ValueX,DateTime? FromDate,DateTime? ToDate)
	    {
		    Discount item = new Discount();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Name = Name;
				
			item.Description = Description;
				
			item.ValueX = ValueX;
				
			item.FromDate = FromDate;
				
			item.ToDate = ToDate;
				
	        item.Save(UserName);
	    }
    }
}
