using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DataAccess
{
    /// <summary>
    /// Controller class for inventory_log
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InventoryLogController
    {
        // Preload our schema..
        InventoryLog thisSchemaLoad = new InventoryLog();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InventoryLogCollection FetchAll()
        {
            InventoryLogCollection coll = new InventoryLogCollection();
            Query qry = new Query(InventoryLog.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InventoryLogCollection FetchByID(object Id)
        {
            InventoryLogCollection coll = new InventoryLogCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InventoryLogCollection FetchByQuery(Query qry)
        {
            InventoryLogCollection coll = new InventoryLogCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (InventoryLog.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (InventoryLog.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int ProductId,int Quantity,int Cost,DateTime CreatedAt)
	    {
		    InventoryLog item = new InventoryLog();
		    
            item.ProductId = ProductId;
            
            item.Quantity = Quantity;
            
            item.Cost = Cost;
            
            item.CreatedAt = CreatedAt;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int ProductId,int Quantity,int Cost,DateTime CreatedAt)
	    {
		    InventoryLog item = new InventoryLog();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.ProductId = ProductId;
				
			item.Quantity = Quantity;
				
			item.Cost = Cost;
				
			item.CreatedAt = CreatedAt;
				
	        item.Save(UserName);
	    }
    }
}
