using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DataAccess
{
    /// <summary>
    /// Controller class for my_tbl
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class MyTblController
    {
        // Preload our schema..
        MyTbl thisSchemaLoad = new MyTbl();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public MyTblCollection FetchAll()
        {
            MyTblCollection coll = new MyTblCollection();
            Query qry = new Query(MyTbl.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public MyTblCollection FetchByID(object Id)
        {
            MyTblCollection coll = new MyTblCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public MyTblCollection FetchByQuery(Query qry)
        {
            MyTblCollection coll = new MyTblCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (MyTbl.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (MyTbl.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int Id,string VarcharColumn1,string VarcharColumn2,string VarcharColumn3,int? IntColumn1,int? IntColumn2,DateTime? CreatedAt,DateTime? UpdatedAt)
	    {
		    MyTbl item = new MyTbl();
		    
            item.Id = Id;
            
            item.VarcharColumn1 = VarcharColumn1;
            
            item.VarcharColumn2 = VarcharColumn2;
            
            item.VarcharColumn3 = VarcharColumn3;
            
            item.IntColumn1 = IntColumn1;
            
            item.IntColumn2 = IntColumn2;
            
            item.CreatedAt = CreatedAt;
            
            item.UpdatedAt = UpdatedAt;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string VarcharColumn1,string VarcharColumn2,string VarcharColumn3,int? IntColumn1,int? IntColumn2,DateTime? CreatedAt,DateTime? UpdatedAt)
	    {
		    MyTbl item = new MyTbl();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.VarcharColumn1 = VarcharColumn1;
				
			item.VarcharColumn2 = VarcharColumn2;
				
			item.VarcharColumn3 = VarcharColumn3;
				
			item.IntColumn1 = IntColumn1;
				
			item.IntColumn2 = IntColumn2;
				
			item.CreatedAt = CreatedAt;
				
			item.UpdatedAt = UpdatedAt;
				
	        item.Save(UserName);
	    }
    }
}
