using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the ProductIngredient class.
	/// </summary>
    [Serializable]
	public partial class ProductIngredientCollection : ActiveList<ProductIngredient, ProductIngredientCollection>
	{	   
		public ProductIngredientCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>ProductIngredientCollection</returns>
		public ProductIngredientCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                ProductIngredient o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the product_ingredients table.
	/// </summary>
	[Serializable]
	public partial class ProductIngredient : ActiveRecord<ProductIngredient>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public ProductIngredient()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public ProductIngredient(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public ProductIngredient(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public ProductIngredient(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("product_ingredients", TableType.Table, DataService.GetInstance("Provider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarProductId = new TableSchema.TableColumn(schema);
				colvarProductId.ColumnName = "product_id";
				colvarProductId.DataType = DbType.Int32;
				colvarProductId.MaxLength = 0;
				colvarProductId.AutoIncrement = false;
				colvarProductId.IsNullable = false;
				colvarProductId.IsPrimaryKey = false;
				colvarProductId.IsForeignKey = true;
				colvarProductId.IsReadOnly = false;
				colvarProductId.DefaultSetting = @"";
				
					colvarProductId.ForeignKeyTableName = "products";
				schema.Columns.Add(colvarProductId);
				
				TableSchema.TableColumn colvarIngredientId = new TableSchema.TableColumn(schema);
				colvarIngredientId.ColumnName = "ingredient_id";
				colvarIngredientId.DataType = DbType.Int32;
				colvarIngredientId.MaxLength = 0;
				colvarIngredientId.AutoIncrement = false;
				colvarIngredientId.IsNullable = false;
				colvarIngredientId.IsPrimaryKey = false;
				colvarIngredientId.IsForeignKey = true;
				colvarIngredientId.IsReadOnly = false;
				colvarIngredientId.DefaultSetting = @"";
				
					colvarIngredientId.ForeignKeyTableName = "ingredients";
				schema.Columns.Add(colvarIngredientId);
				
				TableSchema.TableColumn colvarConsumption = new TableSchema.TableColumn(schema);
				colvarConsumption.ColumnName = "consumption";
				colvarConsumption.DataType = DbType.Int32;
				colvarConsumption.MaxLength = 0;
				colvarConsumption.AutoIncrement = false;
				colvarConsumption.IsNullable = true;
				colvarConsumption.IsPrimaryKey = false;
				colvarConsumption.IsForeignKey = false;
				colvarConsumption.IsReadOnly = false;
				
						colvarConsumption.DefaultSetting = @"((0))";
				colvarConsumption.ForeignKeyTableName = "";
				schema.Columns.Add(colvarConsumption);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Provider"].AddSchema("product_ingredients",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("ProductId")]
		[Bindable(true)]
		public int ProductId 
		{
			get { return GetColumnValue<int>(Columns.ProductId); }
			set { SetColumnValue(Columns.ProductId, value); }
		}
		  
		[XmlAttribute("IngredientId")]
		[Bindable(true)]
		public int IngredientId 
		{
			get { return GetColumnValue<int>(Columns.IngredientId); }
			set { SetColumnValue(Columns.IngredientId, value); }
		}
		  
		[XmlAttribute("Consumption")]
		[Bindable(true)]
		public int? Consumption 
		{
			get { return GetColumnValue<int?>(Columns.Consumption); }
			set { SetColumnValue(Columns.Consumption, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a Ingredient ActiveRecord object related to this ProductIngredient
		/// 
		/// </summary>
		public DataAccess.Ingredient Ingredient
		{
			get { return DataAccess.Ingredient.FetchByID(this.IngredientId); }
			set { SetColumnValue("ingredient_id", value.Id); }
		}
		
		
		/// <summary>
		/// Returns a Product ActiveRecord object related to this ProductIngredient
		/// 
		/// </summary>
		public DataAccess.Product Product
		{
			get { return DataAccess.Product.FetchByID(this.ProductId); }
			set { SetColumnValue("product_id", value.Id); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varProductId,int varIngredientId,int? varConsumption)
		{
			ProductIngredient item = new ProductIngredient();
			
			item.ProductId = varProductId;
			
			item.IngredientId = varIngredientId;
			
			item.Consumption = varConsumption;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int varProductId,int varIngredientId,int? varConsumption)
		{
			ProductIngredient item = new ProductIngredient();
			
				item.Id = varId;
			
				item.ProductId = varProductId;
			
				item.IngredientId = varIngredientId;
			
				item.Consumption = varConsumption;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ProductIdColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IngredientIdColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ConsumptionColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string ProductId = @"product_id";
			 public static string IngredientId = @"ingredient_id";
			 public static string Consumption = @"consumption";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
