using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DataAccess
{
    /// <summary>
    /// Controller class for product_ingredients
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ProductIngredientController
    {
        // Preload our schema..
        ProductIngredient thisSchemaLoad = new ProductIngredient();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ProductIngredientCollection FetchAll()
        {
            ProductIngredientCollection coll = new ProductIngredientCollection();
            Query qry = new Query(ProductIngredient.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ProductIngredientCollection FetchByID(object Id)
        {
            ProductIngredientCollection coll = new ProductIngredientCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ProductIngredientCollection FetchByQuery(Query qry)
        {
            ProductIngredientCollection coll = new ProductIngredientCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (ProductIngredient.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (ProductIngredient.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int ProductId,int IngredientId,int? Consumption)
	    {
		    ProductIngredient item = new ProductIngredient();
		    
            item.ProductId = ProductId;
            
            item.IngredientId = IngredientId;
            
            item.Consumption = Consumption;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int ProductId,int IngredientId,int? Consumption)
	    {
		    ProductIngredient item = new ProductIngredient();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.ProductId = ProductId;
				
			item.IngredientId = IngredientId;
				
			item.Consumption = Consumption;
				
	        item.Save(UserName);
	    }
    }
}
